#!/usr/bin/env bash
# generate-gates.sh — reads frontmatter from plugin/skills/*/SKILL.md and
# produces the GATE skills table for CLAUDE.md.
#
# Detection logic:
#   1. GATE skills have "GATE" or "🚪" in the "# Skill: ..." H1 line.
#   2. Prereqs are extracted from the "**Gate (hard refuse):**" or
#      "**Prereq (hard):**" line in the body (## Inputs section). This avoids
#      grabbing the OUTPUT artefact from "Output: delivery/<slug>/X.md".
#   3. Stage number from "stage NN" in H1.
#
# Usage:
#   bash sdlc/scripts/generate-gates.sh         # print to stdout
#   bash sdlc/scripts/generate-gates.sh --inject sdlc/CLAUDE.md
#                                               # replace marked block in file

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SKILLS_DIR="${ROOT}/plugin/skills"

START_MARKER="<!-- generate-gates:start -->"
END_MARKER="<!-- generate-gates:end -->"

extract_prereq() {
  local file="$1"
  # Find the "Gate (hard refuse)" / "Prereq (hard)" line — extract only
  # `delivery/<slug>/...` backtick paths (skip suggestion-cmd backticks like
  # `sdlc:brainstorm <slug>`).
  local line
  line="$(grep -m1 -E '\*\*(Gate \(hard refuse\)|Prereq \(hard\)|Prereq \(hard refuse\))' "$file" || true)"
  if [ -z "$line" ]; then
    echo "see SKILL.md Inputs"
    return
  fi
  # Extract backticked strings that look like file paths (contain `delivery/`
  # or `.md` or `adr/`). Drop suggestion commands containing `:` or `<slug>`
  # at start.
  echo "$line" | grep -oE '`[^`]+`' \
    | grep -E '(delivery/|\.md|adr/)' \
    | grep -vE '^`sdlc:' \
    | tr '\n' '|' | sed 's/|$//' | sed 's/|/ + /g'
}

emit_rows() {
  for skill_dir in "${SKILLS_DIR}"/*/; do
    skill_file="${skill_dir}SKILL.md"
    [ -f "$skill_file" ] || continue

    h1="$(grep -E '^# Skill:' "$skill_file" | head -1 || true)"
    [ -n "$h1" ] || continue

    # Only GATE skills
    printf '%s' "$h1" | grep -qE 'GATE|🚪' || continue

    stage="$(printf '%s' "$h1" | grep -oE 'stage [0-9]+' | head -1 | awk '{print $2}' || true)"
    [ -n "$stage" ] || stage="99"

    name="$(grep -E '^name:' "$skill_file" | head -1 | sed 's/name: *//')"

    prereq="$(extract_prereq "$skill_file")"

    printf '%s\t%02d 🚪\t`%s`\t%s\n' "$stage" "$stage" "$name" "$prereq"
  done | sort -n | cut -f2-
}

emit_table() {
  printf '%s\n' "${START_MARKER}"
  printf '<!-- Generated by sdlc/scripts/generate-gates.sh — do not edit by hand. Run: make sdlc-docs-gen -->\n'
  printf '\n'
  printf '| Stage | Skill | Hard prereq (refuse if missing) |\n'
  printf '|------:|-------|---------------------------------|\n'
  emit_rows | awk -F'\t' '{ printf "| %s | %s | %s |\n", $1, $2, $3 }'
  printf '%s\n' "${END_MARKER}"
}

if [ "${1:-}" = "--inject" ]; then
  target="${2:?Usage: $0 --inject <file>}"
  [ -f "$target" ] || { echo "no such file: $target" >&2; exit 1; }

  table="$(emit_table)"
  # Use python for safer block replacement (avoids awk multiline string issues)
  python3 - "$target" "$START_MARKER" "$END_MARKER" <<PYEOF
import sys
path, start, end = sys.argv[1], sys.argv[2], sys.argv[3]
table = """$(printf '%s' "$table" | sed 's/"/\\"/g')"""
with open(path) as f:
    src = f.read()
i = src.find(start)
j = src.find(end)
if i == -1 or j == -1 or j < i:
    sys.exit(f"markers not found in {path}")
new = src[:i] + table + src[j + len(end):]
with open(path, 'w') as f:
    f.write(new)
print(f"Updated {path}", file=sys.stderr)
PYEOF
else
  emit_table
fi
